version: '3.3'
services:
  database:
    container_name: docker-local-mysql
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: tama
      MYSQL_USER: the2792
      MYSQL_PASSWORD: canyou12
      MYSQL_ROOT_PASSWORD: canyou12
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  data: